import { useEffect, useRef, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

const inputStyle: React.CSSProperties = { display: "block", width: "100%", height: 48, boxSizing: "border-box", border: "1px solid #d7dedb", borderRadius: 12, background: "#ffffff", color: "#1f2926", padding: "0 12px", fontSize: 16, lineHeight: "24px", outline: "none", WebkitAppearance: "none", appearance: "none", WebkitUserSelect: "text", userSelect: "text", touchAction: "manipulation" };

export function MobileAuth() {
  const [mode, setMode] = useState<"signin" | "signup">("signin");
  const [busy, setBusy] = useState(false);
  const emailRef = useRef<HTMLInputElement>(null); const passwordRef = useRef<HTMLInputElement>(null); const nameRef = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; supabase.auth.getSession().then(({ data }) => { if (active && data.session) window.location.replace("./"); }); return () => { active = false; }; }, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (busy) return; const email = emailRef.current?.value.trim() ?? ""; const password = passwordRef.current?.value ?? ""; const name = nameRef.current?.value.trim() ?? ""; if (!email || !password) return; setBusy(true); try { if (mode === "signup") { const { error } = await supabase.auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin, data: { name } } }); if (error) throw error; } else { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; } window.location.replace("./"); } catch (error) { console.error(error); } finally { setBusy(false); } };
  return <main style={{ minHeight: "100vh", width: "100%", boxSizing: "border-box", padding: "32px 24px", background: "#f8faf9", color: "#1f2926", fontFamily: "system-ui, sans-serif" }}><div style={{ width: "100%", maxWidth: 448, margin: "0 auto" }}><div style={{ marginBottom: 24, textAlign: "center" }}><div style={{ width: 56, height: 56, margin: "0 auto 8px", display: "grid", placeItems: "center", borderRadius: 20, background: "#15977f", color: "white", fontSize: 20, fontWeight: 700 }}>S</div><h1 style={{ margin: 0, fontSize: 24, fontWeight: 800 }}>Spendify</h1><p style={{ margin: "8px 0 0", fontSize: 14, color: "#65716d" }}>Your accounts, spending, budgets and insights in one pocket-sized app.</p></div><form autoComplete="off" onSubmit={submit} style={{ padding: 20, borderRadius: 24, background: "#ffffff", border: "1px solid #e1e7e4" }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 4, padding: 4, marginBottom: 16, borderRadius: 16, background: "#eef3f1" }}><button type="button" onClick={() => setMode("signin")} style={{ height: 40, border: 0, borderRadius: 12, background: mode === "signin" ? "#ffffff" : "transparent", color: "#1f2926", fontWeight: 600 }}>Sign in</button><button type="button" onClick={() => setMode("signup")} style={{ height: 40, border: 0, borderRadius: 12, background: mode === "signup" ? "#ffffff" : "transparent", color: "#1f2926", fontWeight: 600 }}>Create account</button></div>{mode === "signup" && <label style={{ display: "block", marginBottom: 16 }}><span style={{ display: "block", marginBottom: 6, fontSize: 12, fontWeight: 600 }}>Name</span><input ref={nameRef} name="name" autoComplete="off" style={inputStyle} /></label>}<label style={{ display: "block", marginBottom: 16 }}><span style={{ display: "block", marginBottom: 6, fontSize: 12, fontWeight: 600 }}>Email</span><input ref={emailRef} name="email" type="email" autoComplete="off" style={inputStyle} /></label><label style={{ display: "block", marginBottom: 16 }}><span style={{ display: "block", marginBottom: 6, fontSize: 12, fontWeight: 600 }}>Password</span><input ref={passwordRef} name="password" type="password" autoComplete="off" style={inputStyle} /></label><button type="submit" disabled={busy} style={{ width: "100%", height: 48, border: 0, borderRadius: 12, background: "#15977f", color: "white", fontSize: 16, fontWeight: 600 }}>{mode === "signin" ? "Sign in" : "Create account"}</button></form></div></main>;
}
