/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellInsightsRouteImport } from './routes/_shell.insights'
import { Route as ShellTransactionsRouteImport } from './routes/_shell.transactions'
import { Route as ShellAccountsIndexRouteImport } from './routes/_shell.accounts.index'
import { Route as ShellAccountsAccountIdRouteImport } from './routes/_shell.accounts.$accountId'
import { Route as ShellMoreIndexRouteImport } from './routes/_shell.more.index'
import { Route as ShellMoreBudgetsRouteImport } from './routes/_shell.more.budgets'
import { Route as ShellMoreRecurringRouteImport } from './routes/_shell.more.recurring'
import { Route as ShellMoreReportsRouteImport } from './routes/_shell.more.reports'
import { Route as ShellMoreSettingsRouteImport } from './routes/_shell.more.settings'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInsightsRoute = ShellInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransactionsRoute = ShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAccountsIndexRoute = ShellAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAccountsAccountIdRoute = ShellAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMoreIndexRoute = ShellMoreIndexRouteImport.update({
  id: '/more/',
  path: '/more/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMoreBudgetsRoute = ShellMoreBudgetsRouteImport.update({
  id: '/more/budgets',
  path: '/more/budgets',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMoreRecurringRoute = ShellMoreRecurringRouteImport.update({
  id: '/more/recurring',
  path: '/more/recurring',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMoreReportsRoute = ShellMoreReportsRouteImport.update({
  id: '/more/reports',
  path: '/more/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMoreSettingsRoute = ShellMoreSettingsRouteImport.update({
  id: '/more/settings',
  path: '/more/settings',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/auth': typeof AuthRoute
  '/insights': typeof ShellInsightsRoute
  '/transactions': typeof ShellTransactionsRoute
  '/accounts/$accountId': typeof ShellAccountsAccountIdRoute
  '/more/budgets': typeof ShellMoreBudgetsRoute
  '/more/recurring': typeof ShellMoreRecurringRoute
  '/more/reports': typeof ShellMoreReportsRoute
  '/more/settings': typeof ShellMoreSettingsRoute
  '/accounts/': typeof ShellAccountsIndexRoute
  '/more/': typeof ShellMoreIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/insights': typeof ShellInsightsRoute
  '/transactions': typeof ShellTransactionsRoute
  '/': typeof ShellIndexRoute
  '/accounts/$accountId': typeof ShellAccountsAccountIdRoute
  '/more/budgets': typeof ShellMoreBudgetsRoute
  '/more/recurring': typeof ShellMoreRecurringRoute
  '/more/reports': typeof ShellMoreReportsRoute
  '/more/settings': typeof ShellMoreSettingsRoute
  '/accounts': typeof ShellAccountsIndexRoute
  '/more': typeof ShellMoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/_shell/insights': typeof ShellInsightsRoute
  '/_shell/transactions': typeof ShellTransactionsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/accounts/$accountId': typeof ShellAccountsAccountIdRoute
  '/_shell/more/budgets': typeof ShellMoreBudgetsRoute
  '/_shell/more/recurring': typeof ShellMoreRecurringRoute
  '/_shell/more/reports': typeof ShellMoreReportsRoute
  '/_shell/more/settings': typeof ShellMoreSettingsRoute
  '/_shell/accounts/': typeof ShellAccountsIndexRoute
  '/_shell/more/': typeof ShellMoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/insights'
    | '/transactions'
    | '/accounts/$accountId'
    | '/more/budgets'
    | '/more/recurring'
    | '/more/reports'
    | '/more/settings'
    | '/accounts/'
    | '/more/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/insights'
    | '/transactions'
    | '/'
    | '/accounts/$accountId'
    | '/more/budgets'
    | '/more/recurring'
    | '/more/reports'
    | '/more/settings'
    | '/accounts'
    | '/more'
  id:
    | '__root__'
    | '/_shell'
    | '/auth'
    | '/_shell/insights'
    | '/_shell/transactions'
    | '/_shell/'
    | '/_shell/accounts/$accountId'
    | '/_shell/more/budgets'
    | '/_shell/more/recurring'
    | '/_shell/more/reports'
    | '/_shell/more/settings'
    | '/_shell/accounts/'
    | '/_shell/more/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/insights': {
      id: '/_shell/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof ShellInsightsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transactions': {
      id: '/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ShellTransactionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/accounts/': {
      id: '/_shell/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof ShellAccountsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/accounts/$accountId': {
      id: '/_shell/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof ShellAccountsAccountIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/more/': {
      id: '/_shell/more/'
      path: '/more'
      fullPath: '/more/'
      preLoaderRoute: typeof ShellMoreIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/more/budgets': {
      id: '/_shell/more/budgets'
      path: '/more/budgets'
      fullPath: '/more/budgets'
      preLoaderRoute: typeof ShellMoreBudgetsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/more/recurring': {
      id: '/_shell/more/recurring'
      path: '/more/recurring'
      fullPath: '/more/recurring'
      preLoaderRoute: typeof ShellMoreRecurringRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/more/reports': {
      id: '/_shell/more/reports'
      path: '/more/reports'
      fullPath: '/more/reports'
      preLoaderRoute: typeof ShellMoreReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/more/settings': {
      id: '/_shell/more/settings'
      path: '/more/settings'
      fullPath: '/more/settings'
      preLoaderRoute: typeof ShellMoreSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellInsightsRoute: typeof ShellInsightsRoute
  ShellTransactionsRoute: typeof ShellTransactionsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAccountsAccountIdRoute: typeof ShellAccountsAccountIdRoute
  ShellMoreBudgetsRoute: typeof ShellMoreBudgetsRoute
  ShellMoreRecurringRoute: typeof ShellMoreRecurringRoute
  ShellMoreReportsRoute: typeof ShellMoreReportsRoute
  ShellMoreSettingsRoute: typeof ShellMoreSettingsRoute
  ShellAccountsIndexRoute: typeof ShellAccountsIndexRoute
  ShellMoreIndexRoute: typeof ShellMoreIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellInsightsRoute: ShellInsightsRoute,
  ShellTransactionsRoute: ShellTransactionsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellAccountsAccountIdRoute: ShellAccountsAccountIdRoute,
  ShellMoreBudgetsRoute: ShellMoreBudgetsRoute,
  ShellMoreRecurringRoute: ShellMoreRecurringRoute,
  ShellMoreReportsRoute: ShellMoreReportsRoute,
  ShellMoreSettingsRoute: ShellMoreSettingsRoute,
  ShellAccountsIndexRoute: ShellAccountsIndexRoute,
  ShellMoreIndexRoute: ShellMoreIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
